"""
Personaggi giocabili — nomi come in UI italiana (e/o forma internazionale usata nel client IT).

Modulo al livello della repo (non sotto ``core/``) per evitare import circolari con ``core.__init__``.

Aggiornare ``PATCH_ROSTER`` e la tupla ``PERSONAGGI_UFFICIALI`` a ogni patch con nuovi personaggi.

Dedupliche rimosse rispetto a elenchi misti: Childe (→ Tartaglia), Heizou corto (→ Shikanoin Heizou), Sara corto (→ Kujou Sara).
Aggiunti: Vagabondo (IT per Wanderer), Flins; restano anche Traveler, Wanderer e Kyryll per compatibilità DB.
"""
from __future__ import annotations

PATCH_ROSTER = "2026-03"

PERSONAGGI_UFFICIALI: tuple[str, ...] = (
    "Aether",
    "Aino",
    "Albedo",
    "Alhaitham",
    "Aloy",
    "Amber",
    "Arataki Itto",
    "Arlecchino",
    "Ayaka",
    "Ayato",
    "Baizhu",
    "Barbara",
    "Beidou",
    "Bennett",
    "Candace",
    "Charlotte",
    "Chasca",
    "Chevreuse",
    "Chiori",
    "Chongyun",
    "Citlali",
    "Clorinde",
    "Collei",
    "Columbina",
    "Cyno",
    "Dahlia",
    "Dehya",
    "Diluc",
    "Diona",
    "Dori",
    "Durin",
    "Emilie",
    "Escoffier",
    "Eula",
    "Faruzan",
    "Fischl",
    "Flins",
    "Freminet",
    "Furina",
    "Gaming",
    "Ganyu",
    "Gorou",
    "Hu Tao",
    "Iansan",
    "Ifa",
    "Illuga",
    "Ineffa",
    "Jahoda",
    "Jean",
    "Kachina",
    "Kaeya",
    "Kaveh",
    "Kazuha",
    "Keqing",
    "Kinich",
    "Kirara",
    "Klee",
    "Kokomi",
    "Kujou Sara",
    "Kuki Shinobu",
    "Kyryll",
    "Lan Yan",
    "Lauma",
    "Layla",
    "Linnea",
    "Lisa",
    "Lumine",
    "Lynette",
    "Lyney",
    "Mavuika",
    "Mika",
    "Mizuki",
    "Mona",
    "Mualani",
    "Nahida",
    "Navia",
    "Nefer",
    "Neuvillette",
    "Ningguang",
    "Noelle",
    "Ororon",
    "Qiqi",
    "Raiden Shogun",
    "Razor",
    "Rosaria",
    "Sayu",
    "Sethos",
    "Shenhe",
    "Shikanoin Heizou",
    "Sigewinne",
    "Skirk",
    "Sucrose",
    "Tartaglia",
    "Thoma",
    "Tighnari",
    "Traveler",
    "Vagabondo",
    "Varesa",
    "Varka",
    "Venti",
    "Wanderer",
    "Wriothesley",
    "Xiangling",
    "Xianyun",
    "Xiao",
    "Xilonen",
    "Xingqiu",
    "Xinyan",
    "Yae Miko",
    "Yanfei",
    "Yaoyao",
    "Yelan",
    "Yoimiya",
    "Yun Jin",
    "Zhongli",
    "Zibai",
)

# Alias esplicito per codice che preferisce il suffisso _IT
PERSONAGGI_GENSHIN_IT = PERSONAGGI_UFFICIALI
