"""
Nomi arma ufficiali (client italiano). Whitelist DB/UI: solo questi valori (stringa esatta dopo strip).

Manutenzione patch:
  * impostare ``PATCH_ARMI`` alla data/patch di riferimento;
  * aggiungere ogni nuova arma in ``_RAW`` con l’esatta stringa IT del gioco;
  * eseguire i test ``tests/test_nomi_whitelist.py`` dopo l’aggiornamento.
"""
from __future__ import annotations

PATCH_ARMI = "2026-03"

# Tutti i nomi distinti; ``ARMI_UFFICIALI`` è ordinato e deduplicato in coda al modulo.
_RAW: tuple[str, ...] = (
    '"Spada magica del Super Signore Supremo"',
    "Acquamarina di Makhaira",
    "Affettavette",
    "Agata di Rupenera",
    "Aiutante del porto",
    "Alabarda",
    "Alba della Tessiluna",
    "Anello di Hakushin",
    "Anello di Yaxche",
    "Appunti dell'apprendista",
    "Aqua simulacra",
    "Arco ammazzademoni",
    "Arco composto",
    "Arco corvino",
    "Arco da caccia",
    "Arco da caccia per esperti",
    "Arco da caccia smeraldo",
    "Arco da guerra di Favonius",
    "Arco da guerra di Rupenera",
    "Arco di Amos",
    "Arco pluviale del serpente arcobaleno",
    "Arco reale",
    "Arco ricurvo",
    "Arco sacrificale",
    "Argento astrale delle nevi",
    "Arpa celeste",
    "Assoluzione",
    "Aquila Favonia",
    "Astro del vespro errante",
    "Athame Artis",
    "Atlante celeste",
    "Aureola frammentata",
    "Ballata dei fiordi",
    "Ballata del blu sempiterno",
    "Bastone delle sabbie scarlatte",
    "Bastone del sacrificio",
    "Bastone di Homa",
    "Bastone parlante",
    "Battito tonante",
    "Becco d'ibis",
    "Brina mattutina",
    "Cacciatore urbano",
    "Calamità di Eshu",
    "Candido cuore della pioggia",
    "Canto del silenzio",
    "Canto della gru echeggiante",
    "Canzone della Pattuglia delle Sommità",
    "Canzone silvestre",
    "Chiarore di Xiphos",
    "Chiave del Khaj-Nisut",
    "Chiave maestra",
    "Chiodo reggimonti",
    "Codice di Favonius",
    "Corno cinereo",
    "Corrente d'acqua pura",
    "Crepuscolo tenue",
    "Cronache dell'alba",
    "Desiderio purulento",
    "Dialoghi dei saggi del deserto",
    "Elegia di Lumidouce",
    "Elegia finale",
    "Epiche gesta degli Ammazzadraghi",
    "Equa ricompensa",
    "Erede del sole ardente",
    "Faro del Mare dei Giunchi",
    "Fendiluvio",
    "Fiabe di Dodoco",
    "Finale degli abissi",
    "Fionda",
    "Fiore corazzato",
    "Flagello delle calamità",
    "Flauto",
    "Flauto di Ezpitzal",
    "Forma della Luna cremisi",
    "Forgianuvole",
    "Frammenti sacrificali",
    "Frammento lunare portaluce",
    "Frutto della sazietà",
    "Fulgore delle placide acque",
    "Fulmine fagocitante",
    "Gancio fruttuoso",
    "Gancio trappola",
    "Gesta del Lupo maestoso",
    "Giada sacrificale",
    "Giuramento di libertà",
    "Gloria della foresta",
    "Grande lama di Rupenera",
    "Grimorio reale",
    "Grimorio tascabile",
    "Haran Geppaku Futsu",
    "Indicatore distanziometrico",
    "Intuizione pirogenita",
    "Kagotsurube Isshin",
    "Katsuragikiri Nagamasa",
    "La Preda",
    "Lama affilata",
    "Lama celeste",
    "Lama del mercenario",
    "Lama di alburno",
    "Lama fredda",
    "Lama litica",
    "Lama smussata",
    "Lancia crociata di Kitain",
    "Lancia d'osso celeste",
    "Lancia del duello",
    "Lancia del Picco del Drago",
    "Lancia del principiante",
    "Lancia di Favonius",
    "Lancia di giada primordiale",
    "Lancia di mezzaluna",
    "Lancia di Rupenera",
    "Lancia litica",
    "Lancia reale",
    "Lanterna del midollo nero",
    "Liutofuso lucetereo",
    "Luce azzurra",
    "Luce nei vicoli",
    "Lume del Taglio frondoso",
    "Luna di Mouun",
    "Luna perenne",
    "Manuale di magia",
    "Mappa mare",
    "Mareombra",
    "Mazza della persuasione",
    "Memorie terrene",
    "Messaggera dell'alba",
    "Messaggero",
    "Mille sogni fluttuanti",
    "Mille soli ardenti",
    "Missiva del vento",
    "Monocorda",
    "Nefrite gemella",
    "Occhio del giuramento",
    "Occhio della percezione",
    "Ode al Florvento",
    "Ombra di ferro",
    "Ombracandida",
    "Orgoglio celeste",
    "Origine dei venti sacri",
    "Orme iridate",
    "Ossidazione meschina",
    "Osso tenace",
    "Pala del prospettore",
    "Patto del cecchino",
    "Pennacchio bianco",
    "Pennacchio nero",
    "Perla solare",
    "Pensieri vivaci",
    "Pesce da lenza",
    "Pinna del Frangionde",
    "Piuma cremisi dell'avvoltoio astrale",
    "Piume coronate di fiori",
    "Predatore",
    "Prima grande magia",
    "Progressione della solitudine",
    "Prototipo arcaico",
    "Prototipo d'ambra",
    "Prototipo del rancore",
    "Prototipo di Luce stellare",
    "Prototipo di mezzaluna",
    "Punta di ferro",
    "Reliquiario della verità",
    "Richiamo della serenità",
    "Rimembranza di Tulaytullah",
    "Rovine insanguinate",
    "Ruggito del leone",
    "Scacciadraghi",
    "Scudiere del re",
    "Sega elettrica portatile",
    "Sentiero del cacciatore",
    "Serbagelo",
    "Sfera smeraldina",
    "Sinfonia errante",
    "Sinfonista di fragranze",
    "Sipario del notturno",
    "Sisma",
    "Sonnellino mattutino",
    "Spaccarocce Cornorosso",
    "Spadone dell'incapace",
    "Spadone del Cavalcacieli",
    "Spadone del tempo",
    "Spadone di Favonius",
    "Spadone di ferro bianco",
    "Spadone grezzo",
    "Spadone insanguinato",
    "Spadone reale",
    "Spadone sacrificale",
    "Spada cinabrica",
    "Spada d'argento",
    "Spada d'osso di serpente",
    "Spada della discensione",
    "Spada delle ombre",
    "Spada del Cavalcacieli",
    "Spada del viaggiatore",
    "Spada di Akuou",
    "Spada di Favonius",
    "Spada di giada primordiale",
    "Spada di ferro scuro",
    "Spada di Narzissenkreuz",
    "Spada lunga di Rupenera",
    "Spada lunga reale",
    "Spada nera",
    "Spada sacrificale",
    "Spezzacatene",
    "Specchio dell'Intessinotte",
    "Splendore del Giadiluvio",
    "Spina di ferro",
    "Squarcianebbia riforgiata",
    "Squarciavortice",
    "Stella polare",
    "Storie dell'altro mondo",
    "Supervisione pecuniaria",
    "Tamayuratei no Ohanashi",
    "Tomo del flusso perenne",
    "Toukabou Shigure",
    "Trafiggiluna",
    "Traghettatore del Fleuve Cendre",
    "Trapasso ululante",
    "Trivella mineraria",
    "Uraku Misugiri",
    "Vai col surf",
    "Valzer notturno",
    "Veglia del Chiamastelle",
    "Verdetto",
    "Verità della Kagura",
    "Vino e musica",
    "Vortice del Cavalcaonde",
    "Zanna del Re della Montagna",
    "Zanna di lupo",
)

ARMI_UFFICIALI: tuple[str, ...] = tuple(sorted(set(_RAW), key=lambda s: (s.lower(), s)))
