"""
Nomi pezzo in inglese (client EN) per ogni impronta unica di 5 pezzi IT del catalogo.

Chiave: tupla di ``norm_key_nome`` sui 5 nomi italiani (ordine fiore→corona).
Valore: quintupla EN nello stesso ordine. Usato per suggerimenti e alias → canonico IT.

Fonte: nomi ufficiali wiki/game EN (Genshin Impact Fandom / client), allineati ai pezzi IT
in ``manufatti_ufficiali.CATALOGO_ARTEFATTI``. Aggiornare quando si aggiungono set al catalogo.
"""
from __future__ import annotations

from typing import Dict, Tuple

from core.nome_normalization import norm_key_nome

Five = Tuple[str, str, str, str, str]


def _fp(a: str, b: str, c: str, d: str, e: str) -> Five:
    return tuple(norm_key_nome(x) for x in (a, b, c, d, e))


# Impronta IT (norm) → 5 nomi EN ufficiali
ENGLISH_PEZZI_BY_IT_FINGERPRINT: Dict[Five, Five] = {
    _fp(
        "Amore lontano della fanciulla",
        "Delusione d'amore della fanciulla",
        "Giovinezza effimera della fanciulla",
        "Passatempo della fanciulla",
        "Bellezza evanescente della fanciulla",
    ): (
        "Maiden's Distant Love",
        "Maiden's Ill-Fated Love",
        "Maiden's Passing Youth",
        "Maiden's Fleeting Leisure",
        "Maiden's Fading Beauty",
    ),
    _fp(
        "Fiore dell'aurora",
        "Piuma del crepuscolo",
        "Sera dell'eternità",
        "Calice del firmamento",
        "Corona del sognatore",
    ): (
        "Golden Song's Variation",
        "Golden Bird's Shedding",
        "Golden Era's Prelude",
        "Golden Night's Bustle",
        "Golden Troupe's Reward",
    ),
    _fp(
        "Fiore dell'avventuriere",
        "Piuma dell'avventuriere",
        "Orologio dell'avventuriere",
        "Calice d'oro dell'avventuriere",
        "Bandana dell'avventuriere",
    ): (
        "Adventurer's Flower",
        "Adventurer's Tail Feather",
        "Adventurer's Pocket Watch",
        "Adventurer's Golden Goblet",
        "Adventurer's Bandana",
    ),
    _fp(
        "Rosa del berserker",
        "Piuma blu del berserker",
        "Clessidra del berserker",
        "Calice d'osso del berserker",
        "Maschera da guerra del berserker",
    ): (
        "Berserker's Rose",
        "Berserker's Indigo Feather",
        "Berserker's Timepiece",
        "Berserker's Bone Goblet",
        "Berserker's Battle Mask",
    ),
    _fp(
        "In memoria dei campi smeraldo",
        "Piuma della Cacciatrice smeraldo",
        "Determinazione della Cacciatrice smeraldo",
        "Borraccia della Cacciatrice smeraldo",
        "Diadema della Cacciatrice smeraldo",
    ): (
        "Viridescent Venerer's Flower",
        "Viridescent Venerer's Plume",
        "Viridescent Venerer's Determination",
        "Viridescent Venerer's Vessel",
        "Viridescent Venerer's Diadem",
    ),
    _fp(
        "Fiore della giovinezza",
        "Piuma dell'abbandono",
        "Meridiana perduta",
        "Calice della nostalgia",
        "Maschera del ricordo",
    ): (
        "Forgotten Oath of Days Past",
        "Recollection of Days Past",
        "Echoing Sound From Days Past",
        "Promised Dream of Days Past",
        "Poetry of Days Past",
    ),
    _fp(
        "Fiore di ferro insanguinato",
        "Piuma nera insanguinata",
        "La fine del Cavaliere insanguinato",
        "Calice del Cavaliere insanguinato",
        "Maschera di ferro insanguinata",
    ): (
        "Bloodstained Flower of Iron",
        "Bloodstained Black Plume",
        "Bloodstained Final Hour",
        "Bloodstained Chevalier's Goblet",
        "Bloodstained Iron Mask",
    ),
    _fp(
        "Fiore inossidabile",
        "Piuma del dottore saggio",
        "Tempo sospeso",
        "Calice della trascendenza",
        "Maschera beffarda",
    ): (
        "Bloom of Accession",
        "Plume of Luxury",
        "Ancient Panacea",
        "Ceremonial War-Beast",
        "Mocking Mask",
    ),
    _fp(
        "Fiordacciaio sognante",
        "Piuma del giudizio",
        "Gli anni sommersi",
        "Banchetto mielato",
        "Ombra del re delle sabbie",
    ): (
        "Troupe's Dawnlight",
        "Bard's Arrow Feather",
        "Concert's Final Hour",
        "Wanderer's String-Kettle",
        "Conductor's Top Hat",
    ),
    _fp(
        "Miriade di Ay-Khanoum",
        "Banchetto appassito",
        "Coagulo di un istante",
        "Bottiglia magica del custode dei segreti",
        "Corona d'ametista",
    ): (
        "Ay-Khanoum's Myriad",
        "Wilting Feast",
        "A Moment Congealed",
        "Secret-Keeper's Magic Bottle",
        "Amethyst Crown",
    ),
    _fp(
        "Medaglia del coraggioso",
        "Speranza del coraggioso",
        "Forza d'animo del coraggioso",
        "Esordio del coraggioso",
        "Corona del coraggioso",
    ): (
        "Medal of the Brave",
        "Prospect of the Brave",
        "Fortitude of the Brave",
        "Outset of the Brave",
        "Crown of the Brave",
    ),
    _fp(
        "Cuore del Domatore di tuoni",
        "Piuma del Domatore di tuoni",
        "Clessidra del Domatore di tuoni",
        "Calice del Domatore di tuoni",
        "Diadema del Domatore di tuoni",
    ): (
        "Thundersoother's Heart",
        "Thundersoother's Plume",
        "Thundersoother's Clock",
        "Thundersoother's Goblet",
        "Thundersoother's Diadem",
    ),
    _fp(
        "Loto argentato della dottoressa errante",
        "Piuma di gufo della dottoressa errante",
        "Orologio della dottoressa errante",
        "Vaso per medicinali della dottoressa errante",
        "Fazzoletto della dottoressa errante",
    ): (
        "Traveling Doctor's Silver Lotus",
        "Traveling Doctor's Owl Feather",
        "Traveling Doctor's Pocket Watch",
        "Traveling Doctor's Medicine Pot",
        "Traveling Doctor's Handkerchief",
    ),
    _fp(
        "Fiore dell'aromaspirito",
        "Foglia di giada",
        "Simbolo di giubilo",
        "Tazza della sorgente",
        "Orecchini mutevoli",
    ): (
        "Dreaming Steelbloom",
        "Feather of Judgment",
        "The Sunken Years",
        "Honeyed Final Feast",
        "Shadow of the Sand King",
    ),
    _fp(
        "Tsuba poderosa",
        "Piuma spaccata",
        "Inro della tempesta",
        "Calice scarlatto",
        "Kabuto decorato",
    ): (
        "Tsuba of the Gale",
        "Plumage of the Petrified",
        "Storm Cage",
        "Scarlet Vulture",
        "Ornate Kabuto",
    ),
    _fp(
        "Fiore intrecciato",
        "Freccia della rimembranza",
        "Orologio della rugiada mattutina",
        "Cuore speranzoso",
        "Maschera capricciosa",
    ): (
        "Entangling Bloom",
        "Shaft of Remembrance",
        "Morning Dew's Moment",
        "Hopeful Heart",
        "Capricious Visage",
    ),
    _fp(
        "Fiore del mare",
        "Piuma del Palazzo degli abissi",
        "Ciprea dell'addio",
        "Inro di perle",
        "Corona di Watatsumi",
    ): (
        "Sea-Dyed Blossom",
        "Deep Palace's Plume",
        "Cowry of Parting",
        "Pearl Cage",
        "Crown of Watatsumi",
    ),
    _fp(
        "Fiore dell'esule",
        "Piuma dell'esule",
        "Orologio dell'esule",
        "Calice dell'esule",
        "Corona dell'esule",
    ): (
        "Exile's Flower",
        "Exile's Feather",
        "Exile's Pocket Watch",
        "Exile's Goblet",
        "Exile's Circlet",
    ),
    _fp(
        "Fiore della vitalità",
        "Piuma della luce nascente",
        "Reliquia solare",
        "Patto siglato",
        "Portamento tonante",
    ): (
        "Flowering Life",
        "Feather of Nascent Light",
        "Solar Relic",
        "Moment of the Pact",
        "Thundering Poise",
    ),
    _fp(
        "Compassione dell'Uccello del tuono",
        "Superstite della catastrofe",
        "Clessidra tonante",
        "Presagio di tempesta",
        "Corona dell'invocatore di fulmini",
    ): (
        "Thunderbird's Mercy",
        "Survivor of Catastrophe",
        "Hourglass of Thunder",
        "Omen of Thunderstorm",
        "Thunder Summoner's Crown",
    ),
    _fp(
        "Fermaglio dell'istruttore",
        "Piuma dell'istruttore",
        "Orologio dell'istruttore",
        "Tazza da tè dell'istruttore",
        "Cappello dell'istruttore",
    ): (
        "Instructor's Brooch",
        "Instructor's Feather Accessory",
        "Instructor's Pocket Watch",
        "Instructor's Tea Cup",
        "Instructor's Cap",
    ),
    _fp(
        "Fiore vermiglio del marzialista",
        "Piuma del marzialista",
        "Clessidra ad acqua del marzialista",
        "Coppa da vino del marzialista",
        "Bandana del marzialista",
    ): (
        "Martial Artist's Red Flower",
        "Martial Artist's Feather Accessory",
        "Martial Artist's Water Hourglass",
        "Martial Artist's Wine Cup",
        "Martial Artist's Bandana",
    ),
    _fp(
        "Fiore del paradiso perduto",
        "Piuma del paradiso",
        "Meridiana del paradiso",
        "Calice del paradiso",
        "Corona del paradiso",
    ): (
        "Ay-Khanoum's Myriad",
        "Wilting Feast",
        "A Moment Congealed",
        "Secret-Keeper's Magic Bottle",
        "Amethyst Crown",
    ),
    _fp(
        "Fiore reale",
        "Piuma reale",
        "Orologio reale",
        "Urna d'argento reale",
        "Maschera reale",
    ): (
        "Royal Flora",
        "Royal Plume",
        "Royal Pocket Watch",
        "Royal Silver Urn",
        "Royal Masque",
    ),
    _fp(
        "Loto del bosco",
        "Piuma della chiaroveggenza",
        "Meridiana del branco",
        "Lampada della foresta",
        "Corona del lauro",
    ): (
        "Labyrinth Wayfarer",
        "Scholar of Vines",
        "A Time of Insight",
        "Lamp of the Lost",
        "Laurel Coronet",
    ),
    _fp(
        "Fiore miracoloso",
        "Piuma miracolosa",
        "Clessidra miracolosa",
        "Calice miracoloso",
        "Orecchini miracolosi",
    ): (
        "Tiny Miracle's Flower",
        "Tiny Miracle's Feather",
        "Tiny Miracle's Hourglass",
        "Tiny Miracle's Goblet",
        "Tiny Miracle's Earrings",
    ),
    _fp(
        "Memorie nella neve",
        "Risolutezza del Rompighiaccio",
        "Declino della terra del gelo",
        "Dignità gelata",
        "Eco dell'inverno",
    ): (
        "Snowswept Memory",
        "Icebreaker's Resolve",
        "Frozen Homeland's Demise",
        "Frost-Weaved Dignity",
        "Broken Rift's Echo",
    ),
    _fp(
        "Fiore delle notti d'estate",
        "Gran finale delle notti d'estate",
        "Orologio delle notti d'estate",
        "Pallone d'acqua delle notti d'estate",
        "Maschera delle notti d'estate",
    ): (
        "Summer Night's Bloom",
        "Summer Night's Finale",
        "Summer Night's Moment",
        "Summer Night's Waterballoon",
        "Summer Night's Mask",
    ),
    _fp(
        "Primi giorni della Città dei Re",
        "Fine del regno dorato",
        "Orologio del sentiero perduto",
        "Difensore dei sogni ammalianti",
        "Lascito della nobiltà del deserto",
    ): (
        "The First Days of the City of Kings",
        "End of the Golden Realm",
        "Timepiece of the Lost Path",
        "Defender of the Enchanting Dream",
        "Legacy of the Desert High-Born",
    ),
    _fp(
        "Quadrifoglio di Fortunello",
        "Piuma d'aquila di Fortunello",
        "Clessidra di Fortunello",
        "Calice di Fortunello",
        "Corona d'argento di Fortunello",
    ): (
        "Lucky Dog's Clover",
        "Lucky Dog's Eagle Feather",
        "Lucky Dog's Hourglass",
        "Lucky Dog's Goblet",
        "Lucky Dog's Silver Circlet",
    ),
    _fp(
        "Fiore dell'onore",
        "Piuma da guerra cerimoniale",
        "Meridiana d'oricalco",
        "Calice del giuramento del nobile",
        "Elmetto antico del generale",
    ): (
        "Royal Flora",
        "Royal Plume",
        "Royal Pocket Watch",
        "Royal Silver Urn",
        "Royal Masque",
    ),
    _fp(
        "Fermaglio dorato",
        "Brezza nostalgica",
        "Bussola di rame",
        "Calice degli abissi",
        "Tricorno macchiato di vino",
    ): (
        "Entangling Bloom",
        "Shaft of Remembrance",
        "Morning Dew's Moment",
        "Hopeful Heart",
        "Capricious Visage",
    ),
    _fp(
        "Cuore dell'amicizia",
        "Piuma del ritorno",
        "Meridiana del viandante",
        "Calice del viandante",
        "Corona dell'addio",
    ): (
        "Heart of Comradeship",
        "Feather of Homecoming",
        "Sundial of the Sojourner",
        "Goblet of the Sojourner",
        "Circlet of the Sojourner",
    ),
    _fp(
        "Risoluzione dell'Attraversafuochi",
        "Salvezza dell'Attraversafuochi",
        "Tormento dell'Attraversafuochi",
        "Rivelazione dell'Attraversafuochi",
        "Saggezza dell'Attraversafuochi",
    ): (
        "Lavawalker's Resolution",
        "Lavawalker's Salvation",
        "Lavawalker's Torment",
        "Lavawalker's Epiphany",
        "Lavawalker's Wisdom",
    ),
    _fp(
        "Fiore rupestre",
        "Piuma dei picchi aguzzi",
        "Meridiana di giada perenne",
        "Calice di falesia",
        "Maschera di basalto inerte",
    ): (
        "Flower of Creviced Cliff",
        "Feather of Jagged Peaks",
        "Sundial of Enduring Jade",
        "Goblet of Chiseled Crag",
        "Mask of Solitude Basalt",
    ),
    _fp(
        "Seme della fiamma",
        "Piuma della cenere",
        "Polvere del tempo",
        "Calice dell'eroe",
        "Corona della gloria",
    ): (
        "Beast Tamer's Talisman",
        "Mountain Ranger's Marker",
        "Mystic's Golden Dial",
        "Wandering Scholar's Claw Cup",
        "Demon-Warrior's Feather Mask",
    ),
    _fp(
        "Fermaglio della scommettitrice",
        "Piuma della scommettitrice",
        "Orologio della scommettitrice",
        "Tazza per dadi della scommettitrice",
        "Orecchini della scommettitrice",
    ): (
        "Gambler's Brooch",
        "Gambler's Feather Accessory",
        "Gambler's Pocket Watch",
        "Gambler's Dice Cup",
        "Gambler's Earrings",
    ),
    _fp(
        "Fiore di fuoco della strega",
        "Piuma semprardente della strega",
        "Fine della strega",
        "Fiamme del cuore della strega",
        "Cappello infuocato della strega",
    ): (
        "Witch's Flower of Blaze",
        "Witch's Ever-Burning Plume",
        "Witch's End Time",
        "Witch's Heart of Flames",
        "Witch's Scorching Hat",
    ),
    _fp(
        "Segnalibro della studiosa",
        "Calamo della studiosa",
        "Orologio della studiosa",
        "Tazza per inchiostro della studiosa",
        "Lente della studiosa",
    ): (
        "Scholar's Bookmark",
        "Scholar's Quill",
        "Scholar's Clock",
        "Scholar's Ink Cup",
        "Scholar's Lens",
    ),
    _fp(
        "Nostalgia del gladiatore",
        "Destino del gladiatore",
        "Brama del gladiatore",
        "Ebbrezza del gladiatore",
        "Trionfo del gladiatore",
    ): (
        "Gladiator's Nostalgia",
        "Gladiator's Destiny",
        "Gladiator's Longing",
        "Gladiator's Intoxication",
        "Gladiator's Triumph",
    ),
    _fp(
        "Fiore dell'alba pastorale",
        "Giuramento del brillante alba",
        "Nota nella primavera",
        "Racconto inespresso dell'Heldenepos",
        "Minnesang dell'amore e del lamento",
    ): (
        "Windborne Flower's Spruchdichtung",
        "Dawn's Brilliant Oath",
        "A Note in Spring's Leich",
        "Heldenepos's Unspoken Tale",
        "Minnesang of Love and Lament",
    ),
    _fp(
        "Viandante del labirinto",
        "Studioso dei rampicanti",
        "Un momento di discernimento",
        "Lampada degli smarriti",
        "Corona d'alloro",
    ): (
        "Labyrinth Wayfarer",
        "Scholar of Vines",
        "A Time of Insight",
        "Lamp of the Lost",
        "Laurel Coronet",
    ),
    _fp(
        "Fiore del guardiano",
        "Sigillo del guardiano",
        "Orologio del guardiano",
        "Coppa del guardiano",
        "Benda del guardiano",
    ): (
        "Guardian's Flower",
        "Guardian's Sigil",
        "Guardian's Clock",
        "Guardian's Vessel",
        "Guardian's Bandage",
    ),
    _fp(
        "Luce del mattino della compagnia",
        "Piuma del bardo",
        "Ultimo atto dello spettacolo",
        "Borraccia del vagabondo",
        "Cappello del direttore",
    ): (
        "Troupe's Dawnlight",
        "Bard's Arrow Feather",
        "Concert's Final Hour",
        "Wanderer's String-Kettle",
        "Conductor's Top Hat",
    ),
}
